name: Add Workflow File

on:
  issues:
    type:
     -closed
     -open
  
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  add_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "R.PrasannaMeenakshi@in.bosch.com"
          git config --global user.name "Prasanna"

      - name: Add Workflow File
        run: |
          ORGANIZATION="Prasanna-source31"
          WORKFLOW_PATH=".github/workflows/terrascan.yml"  # Change this path if needed
          WORKFLOW_CONTENT=$(cat $WORKFLOW_PATH | base64 -w 0)
          
          for repo in $(gh repo list $ORGANIZATION --json=name --jq '.[].name'); do
            # Fetch the existing file content and SHA-1 hash
            existing_content=$(gh api -X GET /repos/$ORGANIZATION/$repo/contents/$WORKFLOW_PATH)
            existing_sha=$(echo "$existing_content" | jq -r '.sha')

            # Create or update the file
            gh api -X PUT /repos/$ORGANIZATION/$repo/contents/$WORKFLOW_PATH \
              -F message="Add main workflow" \
              -F content="$WORKFLOW_CONTENT" \
              -F branch=main \
              -F sha="$existing_sha"  # Include the existing SHA-1 hash
            echo "Workflow file added to $repo"
          done

    env:
        GITHUB_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
- name: Send Teams Notification
  if: ${{ always() }}
  env:
    TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
  run: |
    if [[ "${{ job.status }}" == "success" ]]; then
      status_text="succeeded"
      status_color="#36a64f"
    fi

    if [[ "${{ job.status }}" == "failure" ]]; then
      status_text="failed"
      status_color="#d9534f"
    fi

    project_key="${{ steps.get_project_key.outputs.project_key }}"
    report_url="http://20.113.139.49:9000/dashboard?id=$project_key"
    echo "Report URL: $report_url"
    workflow_file_name="${GITHUB_WORKFLOW}"
    workflow_file_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true"
    payload="{
      \"@type\": \"MessageCard\",
      \"themeColor\": \"${status_color}\",
      \"title\": \"GitHub Actions Workflow\",
      \"text\": \"Workflow has ${status_text}: ${{ github.repository }}\",
      \"sections\": [
        {
          \"activityTitle\": \"SonarQube Analysis\",
          \"activitySubtitle\": \"${status_text}\",
          \"activityImage\": \"https://www.sonarqube.org/logos/index/favicon.png\",
          \"facts\": [
            {
              \"name\": \"Repository\",
              \"value\": \"${{ github.repository }}\"
            },
            {
              \"name\": \"Report\",
              \"value\": \"[SonarQube Analysis Report](${report_url})\"
            },
            {
              \"name\": \"Workflow File\",
              \"value\": \"[${workflow_file_name}](${workflow_file_url})\"
            }
          ]
        }
      ]
    }"

    curl -X POST -H "Content-Type: application/json" -d "$payload" $TEAMS_WEBHOOK_URL
