name: Create Project Board Column
on:
  issues:
    types:
      - opened
      - closed
      

jobs:
  create_project_board_column:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Project Board Column
        run: |
          TOKEN="${{secrets.BOARD_1}}"
          REPO="Prasanna-source31/Test"
          COLUMN_NAME="Incoming Issues"
          COLUMN_POSITION=3  # Adjust the position as needed
          echo "TOKEN: $TOKEN"
          echo "REPO: $REPO"
          echo "COLUMN_NAME: $COLUMN_NAME"
          echo "COLUMN_POSITION: $COLUMN_POSITION"

          # Create a new column in the project board
          curl -X POST "https://api.github.com/projects/columns" \
            -H "Authorization: token $TOKEN" \
            -d "{\"name\":\"$COLUMN_NAME\",\"position\":$COLUMN_POSITION}" \
            "https://api.github.com/repos/$REPO/projects/3/columns"
- name: Send Teams Notification
  if: ${{ always() }}
  env:
    TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
  run: |
    if [[ "${{ job.status }}" == "success" ]]; then
      status_text="succeeded"
      status_color="#36a64f"
    fi

    if [[ "${{ job.status }}" == "failure" ]]; then
      status_text="failed"
      status_color="#d9534f"
    fi

    project_key="${{ steps.get_project_key.outputs.project_key }}"
    report_url="http://20.113.139.49:9000/dashboard?id=$project_key"
    echo "Report URL: $report_url"
    workflow_file_name="${GITHUB_WORKFLOW}"
    workflow_file_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true"
    payload="{
      \"@type\": \"MessageCard\",
      \"themeColor\": \"${status_color}\",
      \"title\": \"GitHub Actions Workflow\",
      \"text\": \"Workflow has ${status_text}: ${{ github.repository }}\",
      \"sections\": [
        {
          \"activityTitle\": \"SonarQube Analysis\",
          \"activitySubtitle\": \"${status_text}\",
          \"activityImage\": \"https://www.sonarqube.org/logos/index/favicon.png\",
          \"facts\": [
            {
              \"name\": \"Repository\",
              \"value\": \"${{ github.repository }}\"
            },
            {
              \"name\": \"Report\",
              \"value\": \"[SonarQube Analysis Report](${report_url})\"
            },
            {
              \"name\": \"Workflow File\",
              \"value\": \"[${workflow_file_name}](${workflow_file_url})\"
            }
          ]
        }
      ]
    }"

    curl -X POST -H "Content-Type: application/json" -d "$payload" $TEAMS_WEBHOOK_URL
