name: Apply Branch Protection Rules on Issue Open

on:
  issues:
    types:
      - opened

jobs:
  apply-branch-protection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Apply Branch Protection Rules
      run: |
        # Define your organization and branch protection rule configuration
        ORGANIZATION="Prasanna-source31"
        BRANCH="main"
        BRANCH_TOKEN=${{ secrets.BRANCH_TOKEN }}
        # The above token should have necessary permissions for modifying repositories.

        # Retrieve a list of repositories in your organization
        REPOS_RESPONSE=$(curl -H "Authorization: token $BRANCH_TOKEN" -s "https://api.github.com/users/$ORGANIZATION/repos")
        REPOS=$(echo "$REPOS_RESPONSE" | grep -o "\"full_name\": \"[^\"]*\"" | cut -d '"' -f 4)

        for REPO in $REPOS; do
          # Apply branch protection rules to each repository
          echo "Applying branch protection rules to $REPO..."
          curl -X PUT -H "Authorization: token $BRANCH_TOKEN" -d '{
          "required_status_checks": {
          "strict": true,
          "contexts": []
           },
          "enforce_admins": true,
          "required_pull_request_reviews": {
          "dismissal_restrictions": {},
          "dismiss_stale_reviews": true,
          "require_code_owner_reviews": false,
          "required_approving_review_count": 1
          },
         "restrictions": null
          }' "https://api.github.com/repos/$REPO/branches/$BRANCH/protection"
        done
      env:
        BRANCH_TOKEN: ${{ secrets.BRANCH_TOKEN }}
    
  
