on:
  workflow_call:
   inputs:
      username:
        required: true
        type: string
   secrets:
      token:
        required: true
  
     
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '30 04 * * 1-5'  # Run every day at 10:00 AM (IST)

name: SonarQube scan

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    

        
           

    - name: SonarQube Scan
      id: sonarqube_scan
      uses: sonarsource/sonarqube-scan-action@master
      

      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        


    - name: Send Teams Notification
      if: ${{ always() }}  # Notify regardless of the outcome
      env:
        TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
      run: |
        if [[ "${{ job.status }}" == "success" ]]; then
          status_text="succeeded"
          status_color="#36a64f"
        fi

        if [[ "${{ job.status }}" == "failure" ]]; then
         status_text="failed"
         status_color="#d9534f"
        fi

        project_key="${{ steps.get_project_key.outputs.project_key }}"
        report_url="http://20.113.139.49:9000/dashboard?id=$project_key"
        echo "Report URL: $report_url"
        workflow_file_name="${GITHUB_WORKFLOW}"
        workflow_file_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true"
        payload="{
          \"@type\": \"MessageCard\",
          \"themeColor\": \"${status_color}\",
          \"title\": \"GitHub Actions Workflow\",
          \"text\": \"Workflow has ${status_text}: ${{ github.repository }}\",
          \"sections\": [
            {
              \"activityTitle\": \"SonarQube Analysis\",
              \"activitySubtitle\": \"${status_text}\",
              \"activityImage\": \"https://www.sonarqube.org/logos/index/favicon.png\",
              \"facts\": [
                {
                  \"name\": \"Repository\",
                  \"value\": \"${{ github.repository }}\"
                },
                {
                  \"name\": \"Report\",
                  \"value\": \"[SonarQube Analysis Report](${report_url})\"
                },
                 {
          \"name\": \"Workflow File\",
          \"value\": \"[${workflow_file_name}](${workflow_file_url})\"
        }
              ]
            }
          ]
        }"

        curl -X POST -H "Content-Type: application/json" -d "$payload" $TEAMS_WEBHOOK_URL
