on: [push]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
      # Add the following step to display the Terrascan output
    - name: Display Terrascan Output
      run: |
        echo "Terrascan Output:"
        echo "${{ steps.terrascan.outputs.stdout }}"
